### ISSUE TITLE
Return correct headers for content-type and content-length

### ISSUE THREAD

**Issue by kookster** [PRX/dovetail.prx.org#8]
For type, should be easier, as the encoding should be known

For length, a bit tricky, may not have it exactly until audio concatenation complete
Not sure how to get this.

**Comment by chrisrhoden** [comment]
I still think that using content-encoding chunked seems like a good thing to test

**Comment by kookster** [comment]
@chrisrhoden implemented chunked, and the CDN handles it

https://github.com/PRX/dovetail.prx.org/blob/7e9e3bfa7cc566cb0e8863391ed9c2b0135bb0e9/index.js#L18
